version: "3.9"
services:
  # Base image containing dependencies.
  base:
    image: slam_vdb:base
    build:
      context: ..
      dockerfile: docker/Dockerfile
      args:
        ROS_DISTRO: humble
      target: base
    # Interactive shell
    stdin_open: true
    tty: true
    # Networking and IPC for ROS 2
    network_mode: host
    ipc: host
    # Needed to display graphical applications
    privileged: true
 
  # Overlay image containing the source code.
  overlay:
    extends: base
    image: slam_vdb:overlay
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: overlay

  dev:
    extends: overlay
    image: slam_vdb:dev
    build:
      context: ..
      dockerfile: docker/Dockerfile
      target: dev
      args:
        - UID=${UID:-1000}
        - GID=${UID:-1000}
        - USERNAME=${USERNAME:-devuser}
    volumes:
      # Mount the source code
      - ../slam_vdb_ros:/colcon_ws/src/slam_vdb_ros:rw
      # Mount colcon build artifacts for faster rebuilds
      - .colcon/build/:/colcon_ws/build/:rw
      - .colcon/install/:/colcon_ws/install/:rw
      - .colcon/log/:/colcon_ws/log/:rw
    user: ${USERNAME:-devuser}
    command: sleep infinity