FROM ros:jazzy

# TODO : Add the following packages
# Install ROS packages
# Install OPEN_VDB
# RUN apt-get update && apt-get install -y \
#     libopenvdb-dev \
#     libopenvdb-tools \
#     libopenvdb7 \
#     && rm -rf /var/lib/apt/lists/ 

WORKDIR /root
